version: 2.1

workflows:
  my-workflow:
    jobs:
      - build:
          context:
            - Harpia

jobs:
  build:
    docker:
      - image: cimg/node:19.3.0
    working_directory: ~/workspace
    steps:
      - checkout
      - run:
          command: git config --global user.email "the.harpia.io@gmail.com"
      - run:
          command: git config --global user.name "the-harpia-io"
      - run:
          name: Yarn install
          command: yarn install
      - run:
          name: yarn run build
          command: yarn run build
      - run:
          name: Deploy documentation to GitHub Pages
          command: GIT_USER=the-harpia-io yarn deploy
      - run:
          name: Clone repo
          command: git clone https://github.com/the-harpia-io/harpia-docs.git & cd harpia-docs
      - run:
          name: Switch branch
          command: git checkout gh-pages
      - run:
          name: Create CNAME file
          command: touch CNAME && echo "docs.harpia.io" > CNAME
      - run:
          name: Commit CNAME file
          command: git add && git commit -m "DESCRIBE COMMIT IN A FEW WORDS" && git push -u origin gh-pages